import {
  PlanImplementationLaunchCancelledPayload as ContractsPlanImplementationLaunchCancelledPayloadSchema,
  PlanImplementationLaunchFailedPayload as ContractsPlanImplementationLaunchFailedPayloadSchema,
  PlanImplementationLaunchRequestedPayload as ContractsPlanImplementationLaunchRequestedPayloadSchema,
  PlanImplementationLaunchStartedPayload as ContractsPlanImplementationLaunchStartedPayloadSchema,
  PlanImplementationLaunchWorktreePreparedPayload as ContractsPlanImplementationLaunchWorktreePreparedPayloadSchema,
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  SwarmRunRequestedPayload as ContractsSwarmRunRequestedPayloadSchema,
  SwarmRunStartedPayload as ContractsSwarmRunStartedPayloadSchema,
  SwarmRunIdledPayload as ContractsSwarmRunIdledPayloadSchema,
  SwarmRunPausedPayload as ContractsSwarmRunPausedPayloadSchema,
  SwarmRunResumedPayload as ContractsSwarmRunResumedPayloadSchema,
  SwarmRunBlockedPayload as ContractsSwarmRunBlockedPayloadSchema,
  SwarmRunFailedPayload as ContractsSwarmRunFailedPayloadSchema,
  SwarmRunCancelledPayload as ContractsSwarmRunCancelledPayloadSchema,
  SwarmRunCompletedPayload as ContractsSwarmRunCompletedPayloadSchema,
  SwarmTaskExecutionStartedPayload as ContractsSwarmTaskExecutionStartedPayloadSchema,
  SwarmTaskExecutionCompletedPayload as ContractsSwarmTaskExecutionCompletedPayloadSchema,
  SwarmTaskExecutionFailedPayload as ContractsSwarmTaskExecutionFailedPayloadSchema,
  SwarmTaskExecutionCancelledPayload as ContractsSwarmTaskExecutionCancelledPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
export const PlanImplementationLaunchRequestedPayload =
  ContractsPlanImplementationLaunchRequestedPayloadSchema;
export const PlanImplementationLaunchWorktreePreparedPayload =
  ContractsPlanImplementationLaunchWorktreePreparedPayloadSchema;
export const PlanImplementationLaunchStartedPayload =
  ContractsPlanImplementationLaunchStartedPayloadSchema;
export const PlanImplementationLaunchFailedPayload =
  ContractsPlanImplementationLaunchFailedPayloadSchema;
export const PlanImplementationLaunchCancelledPayload =
  ContractsPlanImplementationLaunchCancelledPayloadSchema;
export const SwarmRunRequestedPayload = ContractsSwarmRunRequestedPayloadSchema;
export const SwarmRunStartedPayload = ContractsSwarmRunStartedPayloadSchema;
export const SwarmRunIdledPayload = ContractsSwarmRunIdledPayloadSchema;
export const SwarmRunPausedPayload = ContractsSwarmRunPausedPayloadSchema;
export const SwarmRunResumedPayload = ContractsSwarmRunResumedPayloadSchema;
export const SwarmRunBlockedPayload = ContractsSwarmRunBlockedPayloadSchema;
export const SwarmRunFailedPayload = ContractsSwarmRunFailedPayloadSchema;
export const SwarmRunCancelledPayload = ContractsSwarmRunCancelledPayloadSchema;
export const SwarmRunCompletedPayload = ContractsSwarmRunCompletedPayloadSchema;
export const SwarmTaskExecutionStartedPayload = ContractsSwarmTaskExecutionStartedPayloadSchema;
export const SwarmTaskExecutionCompletedPayload = ContractsSwarmTaskExecutionCompletedPayloadSchema;
export const SwarmTaskExecutionFailedPayload = ContractsSwarmTaskExecutionFailedPayloadSchema;
export const SwarmTaskExecutionCancelledPayload = ContractsSwarmTaskExecutionCancelledPayloadSchema;
